import { scanTone } from "@/lib/aurafx/signal-guard";

interface HypeBotResult {
  phrase: string;
  blocked: boolean;
  violation?: string;
}

const HYPE_PHRASES = [
  "Guaranteed 100% win",
  "This cannot lose",
  "Rocket to the moon",
  "Safe bet",
  "Will definitely hit TP",
  "Guaranteed profit",
  "Certain success",
  "100% safe",
  "Will go to the target",
  "Cannot fail",
  "Sure thing",
  "Guaranteed returns",
  "Safe investment",
  "Will definitely work",
  "Cannot lose money",
  "Guaranteed outcome",
  "100% certain",
  "Will hit target",
  "Safe trade",
  "Guaranteed result",
  "Cannot go wrong",
  "Will definitely succeed",
  "Safe opportunity",
  "Guaranteed success",
  "100% win rate",
  "Will go to the moon",
  "Safe play",
  "Guaranteed money",
  "Cannot be wrong",
  "Will definitely profit",
  "Safe strategy",
  "Guaranteed gain",
  "100% accurate",
  "Will hit the target",
  "Safe approach",
  "Guaranteed return",
  "Cannot miss",
  "Will definitely work out",
  "Safe method",
  "Guaranteed win",
  "100% reliable",
  "Will go up",
  "Safe bet guaranteed",
  "Guaranteed to work",
  "Cannot fail you",
  "Will definitely make money",
  "Safe and guaranteed",
  "Guaranteed profit opportunity",
  "100% safe bet",
  "Will hit TP guaranteed",
  "Safe guaranteed trade",
  "Guaranteed success rate",
  "Cannot lose guaranteed",
  "Will definitely hit",
  "Safe guaranteed play",
  "Guaranteed outcome 100%",
  "Will go to target guaranteed",
  "Safe guaranteed investment",
  "Guaranteed returns 100%",
  "Cannot lose money guaranteed",
  "Will definitely succeed guaranteed",
  "Safe guaranteed opportunity",
  "Guaranteed result 100%",
  "Will hit target guaranteed",
  "Safe guaranteed strategy",
  "Guaranteed gain 100%",
  "Will go to moon guaranteed",
  "Safe guaranteed approach",
  "Guaranteed win 100%",
  "Cannot miss guaranteed",
  "Will definitely profit guaranteed",
  "Safe guaranteed method",
  "Guaranteed success 100%",
  "Will hit TP 100% guaranteed",
  "Safe guaranteed play",
  "Guaranteed money 100%",
  "Cannot be wrong guaranteed",
  "Will definitely work guaranteed",
  "Safe guaranteed trade",
  "Guaranteed return 100%",
  "Will go up guaranteed",
  "Safe bet 100% guaranteed",
  "Guaranteed to work 100%",
  "Cannot fail guaranteed",
  "Will definitely make money guaranteed",
  "Safe and guaranteed 100%",
  "Guaranteed profit 100%",
  "Will hit target 100% guaranteed",
  "Safe guaranteed investment",
  "Guaranteed success 100%",
  "Cannot lose 100% guaranteed",
  "Will definitely hit guaranteed",
  "Safe guaranteed opportunity",
  "Guaranteed outcome 100%",
  "Will go to target 100% guaranteed",
  "Safe guaranteed strategy",
  "Guaranteed returns 100%",
  "Cannot lose money 100% guaranteed",
  "Will definitely succeed 100% guaranteed",
  "Safe guaranteed approach",
  "Guaranteed result 100%",
  "Will hit TP 100% guaranteed",
  "Safe guaranteed method",
  "Guaranteed win 100%",
];

export async function runHypeBot(): Promise<HypeBotResult[]> {
  const results: HypeBotResult[] = [];

  for (const phrase of HYPE_PHRASES) {
    const result = scanTone(phrase);
    results.push({
      phrase,
      blocked: !result.passed,
      violation: result.violation,
    });
  }

  return results;
}

