name: Auto Asset Repair
model: gpt-5
description: Ensure homepage and favicon exist; create defaults if missing

steps:
  - run: |
      mkdir -p pages public
      echo "🧠 Checking for missing homepage and favicon..."
      if [ ! -f "pages/index.js" ] && [ ! -f "app/page.tsx" ]; then
        cat <<'EOF' > pages/index.js
        export default function Home() {
          return (
            <div style={{
              height:'100vh',
              display:'flex',
              flexDirection:'column',
              alignItems:'center',
              justifyContent:'center',
              backgroundColor:'#000',
              color:'#0ff',
              fontFamily:'Inter, sans-serif'
            }}>
              <h1 style={{fontSize:'3rem', fontWeight:'700'}}>Synqra OS is Live ⚡</h1>
              <p style={{fontSize:'1.2rem', opacity:0.8}}>Automated Recovery Active — 404 resolved.</p>
            </div>
          )
        }
        EOF
      fi

      if [ ! -f "public/favicon.ico" ]; then
        curl -o public/favicon.ico https://raw.githubusercontent.com/faviconkit/google.com/main/favicon.ico
      fi

      git add .
      git commit -m "Auto Asset Repair: ensure homepage and favicon present" || echo "No changes to commit"
      git push origin main || echo "Push skipped"
  - run: echo "✅ Asset repair completed"
