name: Auto Homepage Guardian
trigger: ["postDeploy"]
steps:
  - name: Check homepage
    run: |
      if [ ! -f "pages/index.js" ] && [ ! -f "app/page.tsx" ]; then
        echo "No homepage found — generating default Synqra landing page..."
        mkdir -p pages
        cat <<'EOF' > pages/index.js
        export default function Home() {
          return (
            <div style={{
              height:'100vh',
              display:'flex',
              flexDirection:'column',
              alignItems:'center',
              justifyContent:'center',
              backgroundColor:'#000',
              color:'#fff',
              fontFamily:'Inter, sans-serif'
            }}>
              <h1 style={{fontSize:'3rem', fontWeight:'700', color:'#0ff'}}>Synqra</h1>
              <p style={{fontSize:'1.2rem'}}>Automating content creation for the luxury world ⚡</p>
            </div>
          );
        }
        EOF
        git add pages/index.js
        git commit -m "auto: generated default homepage"
        git push origin main
        railway up
      else
        echo "Homepage exists — no action needed."
      fi
