name: Synqra Status Email
on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Status Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: "Synqra Status Report"
          to: tomford46661@gmail.com
          from: "Synqra Bot <tomford46661@gmail.com>"
          body: "✅ Synqra homepage verified and running at $(date)"
