-- Create table to store asset logs if it doesn't exist
create table if not exists asset_logs (
  id bigint generated by default as identity primary key,
  file_name text not null,
  folder_type text not null,
  file_size_kb numeric,
  created_at timestamptz default now(),
  validation_status text,
  thumbnail_path text,
  width int,
  height int,
  aspect_ratio text
);
