/**
 * Agent Decision Traceability Types
 * Immutable audit logs for human review only
 * 
 * RULES:
 * - Logs are for human audit only
 * - No algorithmic feedback or self-optimization
 * - No user-facing exposure beyond "Assessment generated by X agents"
 */

/**
 * Agent identifier and version
 */
export interface AgentIdentity {
  name: string;           // e.g., "aura-fx-analyzer", "council-voter-1"
  version: string;        // Semantic version: "1.2.3"
  role: AgentRole;        // Agent's role in assessment
}

/**
 * Agent roles in the assessment pipeline
 */
export type AgentRole =
  | "analyzer"           // Primary market analysis
  | "validator"          // Validation and checks
  | "council_voter"      // Council voting member
  | "synthesizer"        // Final synthesis
  | "risk_assessor"      // Risk calculation
  | "signal_generator";  // Signal generation

/**
 * Prompt configuration snapshot
 */
export interface PromptSnapshot {
  version_hash: string;   // SHA-256 hash of prompt template
  template_name: string;  // e.g., "aura-fx-analysis-v2"
  parameters: Record<string, unknown>; // Prompt parameters used
}

/**
 * Reasoning snapshot reference (stored separately)
 */
export interface ReasoningSnapshotRef {
  snapshot_id: string;    // UUID reference to reasoning_snapshots table
  storage_path: string;   // Path to full reasoning data (if external storage)
  size_bytes: number;     // Size of reasoning data
  created_at: string;     // Timestamp
}

/**
 * Complete agent traceability record
 */
export interface AgentTraceabilityRecord {
  id: string;                           // UUID
  assessment_id: string;                // Reference to aura_signals or assessment
  assessment_schema_version: string;    // Schema version at time of assessment
  
  // Agent metadata
  agents: AgentIdentity[];              // All agents involved
  primary_agent: AgentIdentity;         // Primary decision-making agent
  
  // Prompt metadata
  prompt: PromptSnapshot;               // Prompt configuration
  
  // Reasoning snapshot
  reasoning_ref: ReasoningSnapshotRef;  // Reference to reasoning data
  
  // Timestamps
  created_at: string;                   // When assessment was generated
  
  // Immutability marker
  readonly immutable: true;             // Type-level immutability marker
}

/**
 * Reasoning snapshot (stored separately for size management)
 * Contains full agent reasoning chain
 */
export interface ReasoningSnapshot {
  id: string;                           // UUID
  assessment_id: string;                // Reference to assessment
  
  // Raw reasoning data
  reasoning_chain: ReasoningStep[];     // Step-by-step reasoning
  context_used: ContextSnapshot;        // Context/data used
  
  // Metadata
  total_tokens: number;                 // Token usage
  model_used: string;                   // Model identifier
  temperature: number;                  // Model temperature
  
  created_at: string;
  
  // Immutability marker
  readonly immutable: true;
}

/**
 * Individual reasoning step
 */
export interface ReasoningStep {
  step_number: number;
  agent_name: string;
  action: string;                       // e.g., "analyze_chart", "calculate_probability"
  input: Record<string, unknown>;       // Input data
  output: Record<string, unknown>;      // Output data
  reasoning: string;                    // Natural language reasoning
  timestamp: string;
}

/**
 * Context snapshot
 */
export interface ContextSnapshot {
  market_data: {
    symbol: string;
    timeframe: string;
    data_points: number;
    timestamp_range: {
      start: string;
      end: string;
    };
  };
  indicators_used: string[];            // List of indicators
  external_data_sources: string[];      // External APIs called
}

/**
 * User-facing agent attribution (minimal exposure)
 */
export interface AgentAttribution {
  agent_count: number;                  // Number of agents involved
  primary_agent_name: string;           // Primary agent name
  version: string;                      // Primary agent version
  generated_at: string;                 // Timestamp
}

/**
 * Audit log query filters
 */
export interface AuditLogFilters {
  assessment_id?: string;
  agent_name?: string;
  agent_version?: string;
  date_from?: string;
  date_to?: string;
  schema_version?: string;
  limit?: number;
}

/**
 * Audit log query result
 */
export interface AuditLogQueryResult {
  records: AgentTraceabilityRecord[];
  total_count: number;
  page: number;
  page_size: number;
}

/**
 * Prompt version registry entry
 */
export interface PromptVersionRegistry {
  version_hash: string;                 // SHA-256 hash
  template_name: string;
  template_content: string;             // Full prompt template
  parameters_schema: Record<string, unknown>; // JSON schema for parameters
  created_at: string;
  deprecated: boolean;
  deprecation_reason?: string;
}

/**
 * Agent version registry entry
 */
export interface AgentVersionRegistry {
  agent_name: string;
  version: string;                      // Semantic version
  role: AgentRole;
  capabilities: string[];               // List of capabilities
  model_used: string;                   // Model identifier
  deployed_at: string;
  deprecated: boolean;
  deprecation_reason?: string;
}
