"use client";

import { Info } from "lucide-react";
import { useState } from "react";

interface AgentAttributionProps {
  agentCount: number;
  primaryAgentName: string;
  version: string;
  generatedAt: string;
  variant?: "inline" | "footer";
}

/**
 * Minimal user-facing agent attribution
 * Shows only: "Assessment generated by X agents"
 * 
 * RULES:
 * - No detailed agent information exposed
 * - No reasoning or decision details
 * - Simple, non-technical language
 */
export function AgentAttribution({
  agentCount,
  primaryAgentName,
  version,
  generatedAt,
  variant = "inline",
}: AgentAttributionProps) {
  const [showDetails, setShowDetails] = useState(false);

  const formatAgentName = (name: string): string => {
    // Convert technical names to user-friendly format
    const nameMap: Record<string, string> = {
      "aura-fx-analyzer": "AuraFX Analysis",
      "council-voter-1": "Council Validator",
      "signal-generator": "Signal Generator",
      "risk-assessor": "Risk Assessor",
    };
    return nameMap[name] || name;
  };

  const formatDate = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleString(undefined, {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  if (variant === "footer") {
    return (
      <div className="mt-6 pt-4 border-t border-noid-silver/10">
        <div className="flex items-center justify-between text-xs text-noid-silver/50">
          <span>
            Assessment generated by {agentCount} agent{agentCount !== 1 ? "s" : ""}
          </span>
          <span>{formatDate(generatedAt)}</span>
        </div>
      </div>
    );
  }

  return (
    <div className="relative">
      <button
        onClick={() => setShowDetails(!showDetails)}
        className="flex items-center gap-2 text-xs text-noid-silver/60 hover:text-noid-silver/80 transition-colors"
      >
        <Info className="h-3 w-3" />
        <span>
          Assessment generated by {agentCount} agent{agentCount !== 1 ? "s" : ""}
        </span>
      </button>

      {showDetails && (
        <div className="absolute top-full left-0 mt-2 z-10 w-64 rounded-lg border border-noid-silver/20 bg-noid-black p-3 shadow-lg">
          <div className="space-y-2 text-xs">
            <div>
              <span className="text-noid-silver/50">Primary Agent:</span>
              <span className="ml-2 text-noid-silver">
                {formatAgentName(primaryAgentName)}
              </span>
            </div>
            <div>
              <span className="text-noid-silver/50">Version:</span>
              <span className="ml-2 text-noid-silver font-mono">{version}</span>
            </div>
            <div>
              <span className="text-noid-silver/50">Generated:</span>
              <span className="ml-2 text-noid-silver">{formatDate(generatedAt)}</span>
            </div>
            <div className="pt-2 mt-2 border-t border-noid-silver/10 text-noid-silver/40">
              Agent decisions are logged for quality assurance and audit purposes.
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/**
 * Compact version for list views
 */
export function CompactAgentAttribution({
  agentCount,
  generatedAt,
}: {
  agentCount: number;
  generatedAt: string;
}) {
  return (
    <div className="flex items-center gap-2 text-xs text-noid-silver/50">
      <Info className="h-3 w-3" />
      <span>
        {agentCount} agent{agentCount !== 1 ? "s" : ""}
      </span>
      <span>•</span>
      <span>{new Date(generatedAt).toLocaleTimeString()}</span>
    </div>
  );
}
