name: Bug report
description: Create a report to help us improve
labels: [bug]
title: "bug: "
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: App version or commit SHA
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste relevant logs.
      render: shell
    validations:
      required: false
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, Node version, browser, etc.
    validations:
      required: false
