import type {
  PricingTier,
  PricingTierSlug,
  PricingConfig,
} from "@/types/pricing";

export const DEFAULT_FALLBACK_TIER: PricingTierSlug = "creator";

// TODO(stripe): Keep these marketing details aligned with Stripe products once they are provisioned.
export const pricingConfig: PricingConfig = {
  free: {
    slug: "free",
    name: "Draft",
    price: 0,
    priceLabel: "$0",
    currency: "USD",
    billingInterval: "custom",
    campaignsPerInterval: 2,
    intervalLabel: "lifetime",
    badge: undefined,
    highlight: false,
    description: "Experiment inside the studio with limited campaigns.",
    includesWatermark: true,
    maxResolution: "720p",
    includesUnlimitedUsers: false,
    supportLevel: "self-serve",
    features: [
      "Watermarked output",
      "Max 2 campaigns total",
      "Single style/template access",
      "No automation flows",
      "Slower queue (24h)",
    ],
    cta: {
      label: "Start Free",
      href: "/signup",
      variant: "primary",
    },
  },
  explorer: {
    slug: "explorer",
    name: "Explorer",
    price: 79,
    priceLabel: "$79",
    currency: "USD",
    billingInterval: "weekly",
    campaignsPerInterval: 4,
    intervalLabel: "per week",
    badge: "Test Drive",
    highlight: false,
    description: "Pilot Synqra with fast-turn weekly output.",
    includesWatermark: false,
    maxResolution: "1080p",
    includesUnlimitedUsers: false,
    supportLevel: "self-serve",
    features: [
      "4 campaigns / week",
      "1 automation flow",
      "Priority over Free tier",
      "Switch to Monthly & save 40%+",
    ],
    cta: {
      label: "Start Weekly",
      href: "/checkout/explorer",
      variant: "primary",
    },
  },
  creator: {
    slug: "creator",
    name: "Atelier",
    price: 197,
    priceLabel: "$197",
    currency: "USD",
    billingInterval: "monthly",
    campaignsPerInterval: 12,
    intervalLabel: "per month",
    badge: undefined,
    highlight: false,
    description: "Monthly cadence with high-res delivery.",
    includesWatermark: false,
    maxResolution: "1080p",
    includesUnlimitedUsers: false,
    supportLevel: "self-serve",
    features: [
      "12 campaigns / month",
      "High-res export (1080p)",
      "3 automation flows",
      "Access to premium styles",
    ],
    cta: {
      label: "Choose Atelier",
      href: "/checkout/atelier",
      variant: "primary",
    },
  },
  team: {
    slug: "team",
    name: "Couture",
    price: 497,
    priceLabel: "$497",
    currency: "USD",
    billingInterval: "monthly",
    campaignsPerInterval: 40,
    intervalLabel: "per month",
    badge: "Most Popular",
    highlight: true,
    description: "Scale across channels with team collaboration.",
    includesWatermark: false,
    maxResolution: "1080p",
    includesUnlimitedUsers: false,
    supportLevel: "concierge",
    features: [
      "40 campaigns / month",
      "5 seats, 10 automation flows",
      "Priority processing",
      "Premium styles & templates",
    ],
    cta: {
      label: "Choose Couture",
      href: "/checkout/couture",
      variant: "primary",
    },
  },
  studio: {
    slug: "studio",
    name: "Maison",
    price: 1297,
    priceLabel: "$1,297",
    currency: "USD",
    billingInterval: "monthly",
    campaignsPerInterval: 100,
    intervalLabel: "per month",
    badge: undefined,
    highlight: false,
    description: "Unlimited creative direction with API access.",
    includesWatermark: false,
    maxResolution: "4k",
    includesUnlimitedUsers: true,
    supportLevel: "dedicated",
    features: [
      "100 campaigns / month",
      "Unlimited seats, 25 automation flows",
      "API access (bandwidth-limited)",
      "Dedicated onboarding",
    ],
    cta: {
      label: "Choose Maison",
      href: "/checkout/maison",
      variant: "primary",
    },
  },
  enterprise: {
    slug: "enterprise",
    name: "Enterprise",
    price: null,
    priceLabel: "Contact Us",
    currency: "USD",
    billingInterval: "custom",
    campaignsPerInterval: null,
    intervalLabel: "custom",
    badge: undefined,
    highlight: false,
    description: "Private infrastructure, dedicated support, and bespoke SLAs.",
    includesWatermark: false,
    maxResolution: "4k",
    includesUnlimitedUsers: true,
    supportLevel: "dedicated",
    features: [
      "Custom SLAs & support",
      "Advanced API & SSO",
      "Security reviews & compliance",
    ],
    cta: {
      label: "Request Proposal",
      href: "/contact?type=enterprise",
      variant: "secondary",
      external: false,
      contactOnly: true,
    },
  },
};

export const PRICING_SLUGS = Object.keys(pricingConfig) as PricingTierSlug[];

export function getPricingTier(slug: PricingTierSlug): PricingTier {
  return pricingConfig[slug] ?? pricingConfig[DEFAULT_FALLBACK_TIER];
}
