name: Synqra Health Logger
trigger:
  - schedule: "0 9 * * *"    # runs every day at 9 AM
env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
steps:
  - name: Check Synqra status
    run: |
      STATUS=$(curl -Is https://synqra.co | head -n 1 | grep "200")
      if [ -z "$STATUS" ]; then
        HEALTH="DOWN"
      else
        HEALTH="UP"
      fi
      echo "Health=$HEALTH"
      echo "Timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
      echo "$HEALTH,$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > health.csv

  - name: Store log in Supabase
    uses: supabase/insert
    with:
      table: "synqra_health_logs"
      data: |
        {
          "status": "${{ steps.Check Synqra status.output.Health }}",
          "timestamp": "${{ steps.Check Synqra status.output.Timestamp }}"
        }

  - name: Weekly report
    if: ${{ date '+%u' == '7' }}   # only on Sundays
    uses: supabase/generate-pdf
    with:
      query: "SELECT * FROM synqra_health_logs WHERE timestamp >= now() - interval '7 days'"
      filename: "synqra-weekly-digest.pdf"
      send_to: "tomford46661@gmail.com"
      subject: "Synqra Weekly Health Digest"
      message: "Attached is your automated uptime summary for the past week."