name: Synqra Auto-Heal Guardian
trigger:
  - schedule: "*/30 * * * *"    # every 30 minutes

# Environment variables are provided by your secrets store
# If running in Cursor Agents or GitHub Actions, map from secrets accordingly
env:
  RAILWAY_TOKEN: "${{ secrets.RAILWAY_TOKEN }}"
  RESEND_API_KEY: "${{ secrets.RESEND_API_KEY || '' }}"
  SENDGRID_API_KEY: "${{ secrets.SENDGRID_API_KEY || '' }}"

steps:
  - name: Health-check Synqra
    id: health
    run: |
      set -euo pipefail
      STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://synqra.co)
      echo "status_code=$STATUS_CODE" >> "$GITHUB_OUTPUT"
      if [ "$STATUS_CODE" != "200" ]; then
        echo "⚠️  Synqra not responding — initiating redeploy..."
        railway redeploy --service=synqra-os
        echo "redeployed=true" >> "$GITHUB_OUTPUT"
      else
        echo "✅  Synqra healthy (HTTP 200)."
        echo "redeployed=false" >> "$GITHUB_OUTPUT"
      fi

  - name: Notify status via Resend
    if: ${{ env.RESEND_API_KEY != '' }}
    run: |
      NOW=$(date -Is)
      curl -s -X POST https://api.resend.com/emails \
        -H "Authorization: Bearer ${RESEND_API_KEY}" \
        -H "Content-Type: application/json" \
        -d @- <<'JSON'
      {
        "from": "Synqra Bot <noreply@synqra.co>",
        "to": ["tomford46661@gmail.com"],
        "subject": "Synqra Auto-Heal Report",
        "html": "Status Code: ${{ steps.health.outputs.status_code }}<br/>Redeployed: ${{ steps.health.outputs.redeployed }}<br/>Time: ${NOW}"
      }
JSON

  - name: Notify status via SendGrid (fallback)
    if: ${{ env.RESEND_API_KEY == '' && env.SENDGRID_API_KEY != '' }}
    run: |
      NOW=$(date -Is)
      curl -s -X POST https://api.sendgrid.com/v3/mail/send \
        -H "Authorization: Bearer ${SENDGRID_API_KEY}" \
        -H "Content-Type: application/json" \
        -d @- <<'JSON'
      {
        "personalizations": [{ "to": [{ "email": "tomford46661@gmail.com" }] }],
        "from": { "email": "noreply@synqra.co" },
        "subject": "Synqra Auto-Heal Report",
        "content": [{ "type": "text/html", "value": "Status Code: ${{ steps.health.outputs.status_code }}<br/>Redeployed: ${{ steps.health.outputs.redeployed }}<br/>Time: ${NOW}" }]
      }
JSON
