export const metadata = {
  title: "Terms - Synqra",
  description: "Synqra terms of use.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto min-h-screen w-full max-w-3xl px-6 py-12 text-white">
      <h1 className="text-3xl font-semibold tracking-tight">Terms</h1>
      <p className="mt-3 text-sm text-white/70">Last updated: February 10, 2026</p>

      <section className="mt-8 space-y-4 text-sm leading-7 text-white/85">
        <p>
          By using Synqra, you agree to use the service lawfully and provide accurate information during onboarding and
          account setup.
        </p>
        <p>
          Output generated by the product should be reviewed before publication. You are responsible for final use of
          generated content and assets.
        </p>
        <p>
          Service availability may change during pilot periods. We may update, pause, or limit access to maintain
          reliability and security.
        </p>
        <p>
          Questions about these terms can be sent to{" "}
          <a className="text-[#D4AF37] underline" href="mailto:support@synqra.co">
            support@synqra.co
          </a>
          .
        </p>
      </section>
    </main>
  );
}
