(()=>{var e={};e.id=3519,e.ids=[3519],e.modules={846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},4870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},9294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},3033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},9023:(e,r,t)=>{"use strict";t.r(r),t.d(r,{patchFetch:()=>C,routeModule:()=>S,serverHooks:()=>T,workAsyncStorage:()=>b,workUnitAsyncStorage:()=>R});var a={};t.r(a),t.d(a,{GET:()=>P,POST:()=>k});var s=t(1271),i=t(1232),n=t(8079),o=t(1238);let u={draft:"Perfect Draft (first pass):",rewrite:"Perfect Draft (rewrite):",summary:"Perfect Draft (summary):",email:"Perfect Draft (email):"},p={email:"Adjust the sign-off to match your voice, then send.",summary:"This summary keeps clarity, relevance, and momentum.",rewrite:"This rewrite is tightened for executive clarity and forward motion.",draft:"Review for accuracy, then publish with confidence."},m={email:"email",inbox:"email",outreach:"email",summarize:"summary",summary:"summary",recap:"summary",rewrite:"rewrite",polish:"rewrite",clean:"rewrite"},l=/[.!?]+$/,d=e=>{if(!e)return e;let r=e.toLowerCase();return r.charAt(0).toUpperCase()+r.slice(1)},c=e=>{let r=e.toLowerCase();for(let[e,t]of Object.entries(m))if(r.includes(e))return t;return"draft"},f=e=>e.split(/\n+/).flatMap(e=>e.split(/[.!?](?=\s|$)/)).map(e=>e.trim()).filter(Boolean),g=(e,r)=>{let t=e.replace(/["'`]/g,"").trim();if(!t)return"";let a=d(t);return l.test(a)?a:`${a}${r%3==0?".":r%3==1?" —":":"}`.replace(/[:—]$/,".")},h=e=>{let r=(e[0]??"Strategic Update").split(" ").slice(0,8).map(e=>d(e)).join(" "),t=e.map(e=>`• ${d(e)}`).join("\n");return`Subject: ${r}

Hi there,

${t}

Warm regards,
Synqra Draft Engine`},y=e=>{let r=e[0]?d(e[0]):"Key Takeaways",t=e.slice(1).map(e=>`- ${d(e)}`),a=t.length?t.join("\n"):"- Core idea distilled with executive clarity.";return`${r}

${a}`},w=e=>e.map((e,r)=>{let t=d(e);return`${t}${l.test(t)?"":"."}${r%2==0?" with a confident, assured tone.":" ensuring the message feels premium."}`}).join("\n\n")||"The message has been rewritten for precision, poise, and immediate deployment.",x=e=>e.length?e.map((r,t)=>{let a=d(r);return l.test(a)?a:t===e.length-1?`${a}.`:`${a};`}).join(" "):"Your idea now reads with clarity, intent, and forward momentum. Add any extra detail and regenerate for a tighter fit.",j=(e,r)=>{switch(e){case"email":return h(r);case"summary":return y(r);case"rewrite":return w(r);default:return x(r)}},v=(e,r)=>e.replace(/\s+/g,"").length>=20?e:`${e} This draft transforms "${r.trim()}" into a message that feels deliberate, premium, and fully articulated.`,$=async(e,r)=>{let t=e.replace(/\s+/g," ").trim(),a=r??c(t),s=j(a,f(t).map(g).filter(Boolean)),i=u[a]??u.draft,n=p[a]??p.draft;return v(`${i}

${s}

${n}`,t)};var q=t(7759);async function k(e){try{let r=await e.json(),t="string"==typeof r?.prompt?r.prompt.trim():"",a=r?.intent,s="string"==typeof r?.email?r.email.trim():"";if(!t)return o.NextResponse.json({error:"Invalid request",message:"Field 'prompt' is required."},{status:400});let i=(e.headers.get("x-synqra-tier")||"").toLowerCase(),n=e.headers.get("x-synqra-fp"),u=e.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||e.headers.get("x-real-ip")||null,p=e.headers.get("user-agent"),m=e.headers.get("authorization");(0,q.u)({tier:m?"premium":"premium"===i||"enterprise"===i?i:"free",fingerprint:n,email:s||e.headers.get("x-synqra-email"),ip:u,userAgent:p});let l=await $(t,a);return o.NextResponse.json({draft:l,intent:a??"draft",timestamp:new Date().toISOString()},{status:200})}catch(e){if(e instanceof q.J)return o.NextResponse.json({error:"Synqra Lite limit",message:e.message},{status:e.status});return console.error("[/api/draft] error",e),o.NextResponse.json({error:"Draft generation failed",message:e instanceof Error?e.message:"Unknown error"},{status:500})}}async function P(){return o.NextResponse.json({endpoint:"/api/draft",method:"POST",description:"Generate a single executive-grade draft from a prompt",requiredFields:["prompt"],optionalFields:["intent"],intents:["draft","rewrite","summary","email"],example:{prompt:"Write a LinkedIn post about...",intent:"draft"}})}let S=new s.AppRouteRouteModule({definition:{kind:i.RouteKind.APP_ROUTE,page:"/api/draft/route",pathname:"/api/draft",filename:"route",bundlePath:"app/api/draft/route"},resolvedPagePath:"C:\\Projects\\Synqra\\apps\\synqra-mvp\\app\\api\\draft\\route.ts",nextConfigOutput:"standalone",userland:a}),{workAsyncStorage:b,workUnitAsyncStorage:R,serverHooks:T}=S;function C(){return(0,n.patchFetch)({workAsyncStorage:b,workUnitAsyncStorage:R})}},7032:()=>{},408:()=>{},7759:(e,r,t)=>{"use strict";t.d(r,{J:()=>a,u:()=>s});class a extends Error{constructor(e,r=429){super(e),this.status=r,this.name="PublicGatekeeperError"}}function s(e){e.tier}}};var r=require("../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),a=r.X(0,[6207,8048],()=>t(9023));module.exports=a})();