name: Sanity Check (Railway Deploy)

on:
  workflow_run:
    workflows: ["CI"]   # 👈 Change if your main deploy workflow is named differently
    types:
      - completed

jobs:
  sanity-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Run Sanity Check Script
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          chmod +x ./check.sh
          ./check.sh

